/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SeoTagsData } from "./models/interfaces";
export namespace Components {
    interface DlcSeoTags {
        "data": SeoTagsData;
    }
}
declare global {
    interface HTMLDlcSeoTagsElement extends Components.DlcSeoTags, HTMLStencilElement {
    }
    var HTMLDlcSeoTagsElement: {
        prototype: HTMLDlcSeoTagsElement;
        new (): HTMLDlcSeoTagsElement;
    };
    interface HTMLElementTagNameMap {
        "dlc-seo-tags": HTMLDlcSeoTagsElement;
    }
}
declare namespace LocalJSX {
    interface DlcSeoTags {
        "data"?: SeoTagsData;
    }
    interface IntrinsicElements {
        "dlc-seo-tags": DlcSeoTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dlc-seo-tags": LocalJSX.DlcSeoTags & JSXBase.HTMLAttributes<HTMLDlcSeoTagsElement>;
        }
    }
}
