# Solo disparar el workflow cuando se haya un push con un tag etiquetado con "deloy-site..."
on:
  push:
    tags:
      - 'Release 🔥*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get package info
        run: PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') \
        && PACKAGE_NAME=$(cat package.json | grep name | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') \
        && RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
      - name: Create release
        run: curl --data '{"tag_name": "v$PACKAGE_VERSION", \
              "target_commitish": "master", \
              "name": "$RELEASE", \
              "body": "Release $RELEASE", \
              "draft": false, \
              "prerelease": false}' \
              https://api.github.com/repos/$GITHUB_REPOSITORY/releases?access_token=$GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}